name: ETL Pipeline

on:
  push:
    branches:
      - main
  # Optional: schedule the ETL job to run daily
  # schedule:
  #   - cron: '0 0 * * *' # Runs at 12:00 AM UTC daily

jobs:
  # 1. Code Quality Job (Linting and Type Checking)
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt flake8 mypy

      - name: Run Flake8 Linter
        run: flake8 . --max-complexity=10 --max-line-length=120

      - name: Run Mypy Type Checker
        run: mypy .

  # 2. Docker Build and Push Job
  build_and_push:
    needs: code_quality  # Only runs if code quality checks pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/resilience-watch:latest
